### ISSUE TITLE
Build fails with FormatException

### ISSUE THREAD

**Issue by MTRNord** [heftapp/graphql_codegen#109]
Hi,

I am running the build command but somehow it keeps complaining about something. The error I get is:

```
FormatException: Invalid UTF-8 byte (at offset 0)
[SEVERE] graphql_codegen:graphql_codegen on lib/api/graphql/otp.graphql:
```

The file contents are (saved as txt to make github happy):
[otp.txt](https://github.com/heftapp/graphql_codegen/files/8984424/otp.txt)

**Comment by MTRNord** [comment]
Seems like this might also be of relevance:

```
[
  "graphql_codegen:graphql_codegen on lib/api/graphql/otp.graphql",
  [
    "",
    "FormatException: Invalid UTF-8 byte (at offset 0)",
    "#0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1755:7)\n#1      Utf8Decoder.convert (dart:convert/utf.dart:351:42)\n#2      Utf8Codec.decode (dart:convert/utf.dart:63:20)\n#3      CachingAssetReader.readAsString.<anonymous closure>.<anonymous closure> (package:build_runner_core/src/asset/cache.dart:95:38)\n#4      _rootRunUnary (dart:async/zone.dart:1434:47)\n#5      _CustomZone.runUnary (dart:async/zone.dart:1335:19)\n<asynchronous suspension>\n#6      GraphQLBuilder.build.<anonymous closure> (package:graphql_codegen/builder.dart:49:25)\n<asynchronous suspension>\n#7      Stream.asyncMap.<anonymous closure>.add (dart:async/stream.dart:742:7)\n<asynchronous suspension>\n"
  ],
  [
    "",
    "FormatException: Invalid UTF-8 byte (at offset 0)",
    "#0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1755:7)\n#1      Utf8Decoder.convert (dart:convert/utf.dart:351:42)\n#2      Utf8Codec.decode (dart:convert/utf.dart:63:20)\n#3      CachingAssetReader.readAsString.<anonymous closure>.<anonymous closure> (package:build_runner_core/src/asset/cache.dart:95:38)\n#4      _rootRunUnary (dart:async/zone.dart:1434:47)\n#5      _CustomZone.runUnary (dart:async/zone.dart:1335:19)\n<asynchronous suspension>\n#6      GraphQLBuilder.build.<anonymous closure> (package:graphql_codegen/builder.dart:49:25)\n<asynchronous suspension>\n#7      Stream.asyncMap.<anonymous closure>.add (dart:async/stream.dart:742:7)\n<asynchronous suspension>\n"
  ]
]
```

**Comment by budde377** [comment]
Can you try and check the encoding of your file? It should probably be `UTF-8`.

**Comment by MTRNord** [comment]
> Can you try and check the encoding of your file? It should probably be `UTF-8`.

According to vscode it is utf-8 without bom.

**Comment by JosephKorel** [comment]
[This helped me](https://stackoverflow.com/a/74822025)
Check the encoding of your `schema.graphql` file. It should be UTF-8
